infrastructures:
  default: local

  local:
    name: CBPA Production Cell
    components:
      aasRegistry:
        baseUrl: "http://localhost:3000/registry"
      submodelRegistry:
        baseUrl: "http://localhost:3000/sm-registry"
      aasRepository:
        baseUrl: "http://localhost:3000/aas-server"
      submodelRepository:
        baseUrl: "http://localhost:3000/aas-server"
      conceptDescriptionRepository:
        baseUrl: "http://localhost:3000/aas-server"
    security:
      type: none
