pid /tmp/nginx.pid;
events {}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    types {
        application/javascript  js mjs;
    }

    server {
        listen 3000;

        # AAS Web UI
        location / {
            alias /usr/src/app/dist/;
            try_files $uri $uri/ /index.html;
        }

        # Reverse proxy: AAS Registry
        location /registry/ {
            proxy_pass http://aas-registry:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Reverse proxy: AAS Server (shells + submodels)
        location /aas-server/ {
            proxy_pass http://aas-server:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Reverse proxy: Submodel Registry
        location /sm-registry/ {
            proxy_pass http://sm-registry:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
